version: '3'
services:
  dbos:
    image: mysql:5.7
    volumes:
       - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redrootmysql
      MYSQL_USER: Harekrishna
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydatabase


  nextcloud:
    image: drupal:latest
    restart: always
    depends_on:
      - dbos
    ports:
      - 12345:80
    volumes:
      - drupal_storage:/var/www/html

volumes:
  mysql_storage:
  drupal_storage: